import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import { IBM_Plex_Sans_Thai_Looped } from "next/font/google";

const ibmThai = IBM_Plex_Sans_Thai_Looped({
  subsets: ["thai", "latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700"], // เลือกเท่าที่ใช้จริง เพื่อลดขนาด
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={ibmThai.className} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}

      >
        <div className="min-h-screeen">
          <div className="pt-[120px] md:pt-[64px]">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
