import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Poppins } from 'next/font/google';
import { Html } from "next/document";
import { IBM_Plex_Sans_Thai_Looped } from "next/font/google";

const ibmThai = IBM_Plex_Sans_Thai_Looped({
  subsets: ["thai", "latin"],
  weight: ["100","200","300","400","500","600","700"], // เลือกเท่าที่ใช้จริง เพื่อลดขนาด
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
  display: 'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th" className={ibmThai.className} >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       
      >
        {children}
      </body>
    </html>
  );
}
